[theme]

primaryColor="#000000"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
enableStaticServing = true

[client]
showSidebarNavigation = false
<<<<<<< HEAD
=======
toolbarMode = "minimal"
>>>>>>> 2450d732be8294214493ca8f73e2309f823bb56d
